### ISSUE TITLE
Using hydra vocabulary for POST mappings seems out of place

### ISSUE THREAD

**Issue by tpluscode** [zazuko/kopflos#28]
I find the reuse of Hydra IRI template mappings for `http://hydra-box.org/schema/variables` a bit misleading.

I think hydra box should define it's own terms. Or https://code.described.at vocabulary should define them

**Comment by bergos** [comment]
For very simple use cases we could keep it. It's actually not extra code, as the GET request gets converted to a graph first and then goes to the HTTP method independent mapping from graph to variables.

But we should add support for better ways to access the incoming graph. Clownface, SimpleRDF or JSON-LD should be supported.
