### ISSUE TITLE
Remove hydra-box triples from ApiDocumentation

### ISSUE THREAD

**Issue by tpluscode** [zazuko/kopflos#30]
Not super important, but I think that the hydra-box-specific triples are implementation details and should not be part of the public ApiDocumentation resource.

**Comment by tpluscode** [comment]
Maybe do so only when `debug: false`?

**Comment by bergos** [comment]
It should be configurable, but it should not be a debug only feature. The Hydra-Box triples could be used to copy the operation and deploy it somewhere else or even run it locally. This could be difficult or doesn't even make sense, when a triplestore is involved, but would be easy for computing operations.
